/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "flbrifppguyxxkgjynxu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsYnJpZnBwZ3V5eHhrZ2p5bnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1ODg5NzgsImV4cCI6MjA3OTE2NDk3OH0.f-frrYNP1loigt8eBhifazgnLrySNnuP_sSFN6jt-ww"